import { sva } from "../../../../../styled-system/css";

export const sidebar = sva({
	slots: [
		"root",
		"rail",
		"railTabs",
		"railTab",
		"railTabIcon",
		"railTabBadge",
		"panel",
		"panelHeader",
		"panelTitle",
		"panelActions",
		"panelAction",
		"panelContent",
		"panelItem",
		"panelItemIcon",
		"panelItemLabel",
		"panelItemSecondary",
		"panelItemClose",
		"resizeHandle",
	],
	base: {
		root: {
			display: "flex",
			flexDirection: "row",
			height: "100%",
			bg: "bg.primary",
			position: "relative",
			flexShrink: 0,
			overflow: "hidden",
		},
		rail: {
			display: "flex",
			flexDirection: "column",
			width: "48px",
			height: "100%",
			pt: "32px",
			pb: "8px",
			gap: "4px",
			alignItems: "center",
			flexShrink: 0,
		},
		railTabs: {
			display: "flex",
			flexDirection: "column",
			gap: "4px",
			alignItems: "center",
			width: "100%",
		},
		railTab: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "36px",
			height: "36px",
			borderRadius: "sm",
			fontSize: "18px",
			lineHeight: 1,
			color: "fg.secondary",
			cursor: "pointer",
			flexShrink: 0,
			position: "relative",
			transition: "all 0.1s ease",
			_hover: {
				bg: "bg.secondary",
				color: "fg.primary",
			},
		},
		railTabIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "20px",
			height: "20px",
		},
		railTabBadge: {
			position: "absolute",
			top: "4px",
			right: "4px",
			minWidth: "14px",
			height: "14px",
			borderRadius: "full",
			bg: "accent",
			color: "fg.inverse",
			fontSize: "9px",
			fontFamily: "body",
			lineHeight: 1,
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			px: "3px",
		},
		panel: {
			display: "flex",
			flexDirection: "column",
			flex: 1,
			minWidth: 0,
			height: "100%",
			overflow: "hidden",
		},
		panelHeader: {
			display: "flex",
			alignItems: "center",
			justifyContent: "space-between",
			height: "36px",
			mt: "32px",
			px: "12px",
			flexShrink: 0,
		},
		panelTitle: {
			fontSize: "11px",
			fontFamily: "body",
			fontWeight: "600",
			color: "fg.muted",
			textTransform: "uppercase",
			letterSpacing: "0.05em",
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		panelActions: {
			display: "flex",
			alignItems: "center",
			gap: "4px",
		},
		panelAction: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "24px",
			height: "24px",
			borderRadius: "sm",
			fontSize: "16px",
			lineHeight: 1,
			color: "fg.muted",
			cursor: "pointer",
			flexShrink: 0,
			_hover: {
				bg: "bg.secondary",
				color: "fg.primary",
			},
		},
		panelContent: {
			display: "flex",
			flexDirection: "column",
			flex: 1,
			overflow: "auto",
			py: "2px",
		},
		panelItem: {
			display: "flex",
			alignItems: "center",
			height: "30px",
			px: "8px",
			gap: "6px",
			fontSize: "12px",
			fontFamily: "body",
			color: "fg.secondary",
			cursor: "pointer",
			flexShrink: 0,
			borderRadius: "sm",
			mx: "4px",
			transition: "all 0.1s ease",
			_hover: {
				bg: "bg.secondary",
				color: "fg.primary",
				"& .panelItemClose": {
					display: "flex",
				},
			},
		},
		panelItemIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "16px",
			height: "16px",
			flexShrink: 0,
		},
		panelItemLabel: {
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
			flex: 1,
		},
		panelItemSecondary: {
			fontSize: "11px",
			fontFamily: "body",
			color: "fg.muted",
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
			flexShrink: 0,
		},
		panelItemClose: {
			display: "none",
			alignItems: "center",
			justifyContent: "center",
			width: "16px",
			height: "16px",
			borderRadius: "sm",
			fontSize: "14px",
			lineHeight: 1,
			color: "fg.muted",
			cursor: "pointer",
			flexShrink: 0,
			_hover: {
				bg: "bg.primary",
				color: "fg.primary",
			},
		},
		resizeHandle: {
			position: "absolute",
			top: 0,
			width: "4px",
			height: "100%",
			cursor: "col-resize",
			zIndex: 10,
			transition: "background 0.15s ease",
			_hover: {
				bg: "accent",
			},
			"&[data-dragging]": {
				bg: "accent",
			},
		},
	},
	variants: {
		activeTab: {
			true: {
				railTab: {
					bg: "bg.tertiary",
					color: "fg.primary",
				},
			},
		},
		activeItem: {
			true: {
				panelItem: {
					bg: "bg.tertiary",
					color: "fg.primary",
				},
			},
		},
		position: {
			left: {
				root: {
					borderRightWidth: "1px",
					borderRightColor: "bg.secondary",
				},
				resizeHandle: {
					right: 0,
				},
			},
			right: {
				root: {
					borderLeftWidth: "1px",
					borderLeftColor: "bg.secondary",
					flexDirection: "row-reverse",
				},
				resizeHandle: {
					left: 0,
				},
			},
		},
		float: {
			true: {
				root: {
					position: "absolute",
					zIndex: 50,
					boxShadow: "lg",
				},
			},
		},
	},
	compoundVariants: [
		{
			float: true,
			position: "left",
			css: { root: { left: 0, top: 0, bottom: 0 } },
		},
		{
			float: true,
			position: "right",
			css: { root: { right: 0, top: 0, bottom: 0 } },
		},
	],
	defaultVariants: {
		position: "left",
	},
});
