import { LibsqlClient } from "@effect/sql-libsql";
import type { Client } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";
import { Effect } from "effect";

// Resolve migrations folder relative to current module.
// In dev (unbundled): import.meta.url is .../src/api/ensure-schema.ts → ../migrations works.
// In prod (bundled by Electrobun): import.meta.url is .../bun/index.js → ./migrations works
// because electrobun.config.ts copies migrations to bun/migrations/.
const DEV_PATH = decodeURIComponent(new URL("../migrations", import.meta.url).pathname);
const BUNDLED_PATH = decodeURIComponent(new URL("./migrations", import.meta.url).pathname);

/**
 * Ensures the database schema is up to date using Drizzle migrations.
 * Migration files are generated by `drizzle-kit generate` from schema definitions.
 * Zero handwritten SQL — drizzle-kit generates everything from the schema files.
 */
export const ensureSchema = Effect.gen(function* () {
	const sql = yield* LibsqlClient.LibsqlClient;
	// LibsqlClient exposes the underlying libsql Client as `.sdk` at runtime
	// (added in make() but not reflected in the public interface type).
	const libsqlClient = (sql as unknown as Record<string, unknown>).sdk as Client | undefined;
	if (!libsqlClient)
		throw new Error(
			"LibsqlClient.sdk not found — @effect/sql-libsql internal API may have changed",
		);
	const db = drizzle(libsqlClient);

	// Try dev path first, fall back to bundled path if migration fails.
	const tryMigrate = (folder: string) => migrate(db, { migrationsFolder: folder });
	yield* Effect.tryPromise({
		try: () => tryMigrate(DEV_PATH).catch(() => tryMigrate(BUNDLED_PATH)),
		catch: (cause) => new Error(`Migration failed: ${String(cause)}`),
	});
});
