import { LibsqlClient } from "@effect/sql-libsql";
import type { Client } from "@libsql/client";
import { drizzle } from "drizzle-orm/libsql";
import { migrate } from "drizzle-orm/libsql/migrator";
import { Effect } from "effect";
import { fileURLToPath } from "node:url";

const migrationsFolder = fileURLToPath(new URL("../migrations", import.meta.url));

/**
 * Ensures the database schema is up to date using Drizzle migrations.
 * Migration files are generated by `drizzle-kit generate` from schema definitions.
 * Zero handwritten SQL — drizzle-kit generates everything from the schema files.
 */
export const ensureSchema = Effect.gen(function* () {
	const sql = yield* LibsqlClient.LibsqlClient;
	// LibsqlClient exposes the underlying libsql Client as `.sdk` at runtime
	// (added in make() but not reflected in the public interface type).
	const libsqlClient = (sql as unknown as { sdk: Client }).sdk;
	const db = drizzle(libsqlClient);
	yield* Effect.tryPromise({
		try: () =>
			migrate(db, {
				migrationsFolder,
			}),
		catch: (cause) => new Error(`Migration failed: ${String(cause)}`),
	});
});
