import { sva } from "../../../../../styled-system/css";

export const commandCenter = sva({
	slots: [
		"overlay",
		"palette",
		"searchBar",
		"searchIcon",
		"searchInput",
		"shortcutBadge",
		"divider",
		"results",
		"sectionLabel",
		"resultItem",
		"resultIcon",
		"resultLabel",
		"resultSecondary",
		"resultBadge",
		"resultBadgeIcon",
		"footer",
		"footerHint",
		"footerHintKey",
		"footerHintLabel",
	],
	base: {
		overlay: {
			position: "fixed",
			inset: 0,
			display: "flex",
			alignItems: "flex-start",
			justifyContent: "center",
			pt: "15vh",
			zIndex: 999999,
			pointerEvents: "none",
		},
		palette: {
			display: "flex",
			flexDirection: "column",
			width: "640px",
			maxHeight: "min(480px, 60vh)",
			bg: "bg.secondary",
			borderRadius: "16px",
			overflow: "hidden",
			boxShadow: "0 0 0 1px rgba(255, 255, 255, 0.08), 0 16px 70px rgba(0, 0, 0, 0.6)",
			pointerEvents: "auto",
		},
		searchBar: {
			display: "flex",
			alignItems: "center",
			height: "52px",
			px: "16px",
			gap: "12px",
			flexShrink: 0,
		},
		searchIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "18px",
			height: "18px",
			color: "fg.muted",
			flexShrink: 0,
		},
		searchInput: {
			flex: 1,
			bg: "transparent",
			border: "none",
			outline: "none",
			fontSize: "13px",
			fontFamily: "body",
			color: "fg.primary",
			_placeholder: {
				color: "fg.muted",
			},
		},
		shortcutBadge: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			height: "22px",
			px: "8px",
			borderRadius: "sm",
			bg: "bg.tertiary",
			fontSize: "10px",
			fontFamily: "body",
			fontWeight: "600",
			color: "fg.muted",
			flexShrink: 0,
		},
		divider: {
			height: "1px",
			bg: "bg.tertiary",
			flexShrink: 0,
		},
		results: {
			display: "flex",
			flexDirection: "column",
			overflow: "auto",
			py: "8px",
			px: "8px",
			gap: "2px",
			flex: 1,
		},
		sectionLabel: {
			fontSize: "9px",
			fontFamily: "body",
			color: "fg.muted",
			px: "8px",
			py: "4px",
		},
		resultItem: {
			display: "flex",
			alignItems: "center",
			height: "40px",
			width: "100%",
			px: "12px",
			gap: "10px",
			borderRadius: "md",
			cursor: "pointer",
			flexShrink: 0,
			fontSize: "13px",
			fontFamily: "body",
			color: "fg.primary",
			border: "none",
			bg: "transparent",
			textAlign: "left",
			transition: "all 0.1s ease",
			_hover: {
				bg: "bg.tertiary",
			},
		},
		resultIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "20px",
			height: "20px",
			borderRadius: "xs",
			flexShrink: 0,
		},
		resultLabel: {
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
			flex: 1,
		},
		resultSecondary: {
			fontSize: "13px",
			fontFamily: "body",
			color: "fg.muted",
			flexShrink: 0,
		},
		resultBadge: {
			display: "flex",
			alignItems: "center",
			gap: "6px",
			height: "24px",
			px: "8px",
			borderRadius: "sm",
			bg: "bg.tertiary",
			fontSize: "10px",
			fontFamily: "body",
			fontWeight: "600",
			color: "fg.muted",
			flexShrink: 0,
		},
		resultBadgeIcon: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			width: "12px",
			height: "12px",
			color: "accent",
		},
		footer: {
			display: "flex",
			alignItems: "center",
			height: "36px",
			px: "16px",
			gap: "16px",
			flexShrink: 0,
		},
		footerHint: {
			display: "flex",
			alignItems: "center",
			gap: "4px",
		},
		footerHintKey: {
			fontSize: "10px",
			fontFamily: "body",
			fontWeight: "600",
			color: "fg.muted",
		},
		footerHintLabel: {
			fontSize: "10px",
			fontFamily: "body",
			color: "fg.secondary",
		},
	},
	variants: {
		activeItem: {
			true: {
				resultItem: {
					bg: "bg.tertiary",
				},
			},
		},
	},
});
