import { sva } from "@styled-system/css";

export const omniBox = sva({
	slots: [
		"root",
		"inputRow",
		"searchIcon",
		"engineBadge",
		"engineBadgeText",
		"input",
		"autocompleteHint",
		"dropdown",
		"divider",
		"suggestionRow",
		"suggestionIcon",
		"suggestionText",
		"suggestionAction",
		"suggestionDash",
		"suggestionKbd",
	],
	base: {
		root: {
			display: "flex",
			flexDirection: "column",
			width: "100%",
			bg: "bg.primary",
			border: "1px solid",
			borderColor: "border",
			userSelect: "none",
			overflow: "hidden",
			boxShadow: "lg",
		},
		inputRow: {
			display: "flex",
			alignItems: "center",
			height: "52px",
			px: "16px",
			gap: "10px",
			bg: "bg.secondary",
		},
		searchIcon: {
			flexShrink: 0,
			width: "20px",
			height: "20px",
			color: "fg.muted",
		},
		engineBadge: {
			display: "flex",
			alignItems: "center",
			justifyContent: "center",
			px: "14px",
			py: "6px",
			borderRadius: "10px",
			bg: "accent.subtle",
			flexShrink: 0,
		},
		engineBadgeText: {
			fontSize: "14px",
			fontWeight: "600",
			color: "fg.primary",
			lineHeight: 1,
		},
		input: {
			flex: 1,
			height: "100%",
			bg: "transparent",
			border: "none",
			color: "fg.primary",
			fontSize: "16px",
			fontFamily: "body",
			outline: "none",
			_placeholder: {
				color: "fg.muted",
			},
		},
		autocompleteHint: {
			fontSize: "16px",
			fontFamily: "body",
			color: "fg.subtle",
			pointerEvents: "none",
		},
		dropdown: {
			display: "flex",
			flexDirection: "column",
		},
		divider: {
			height: "1px",
			bg: "border",
			flexShrink: 0,
		},
		suggestionRow: {
			display: "flex",
			alignItems: "center",
			height: "44px",
			px: "16px",
			gap: "10px",
			cursor: "pointer",
			bg: "bg.primary",
			_hover: {
				bg: "bg.secondary",
			},
		},
		suggestionIcon: {
			flexShrink: 0,
			width: "18px",
			height: "18px",
			color: "fg.muted",
		},
		suggestionText: {
			fontSize: "15px",
			fontFamily: "body",
			color: "fg.secondary",
			overflow: "hidden",
			textOverflow: "ellipsis",
			whiteSpace: "nowrap",
		},
		suggestionDash: {
			fontSize: "15px",
			fontFamily: "body",
			color: "fg.subtle",
			flexShrink: 0,
		},
		suggestionAction: {
			fontSize: "15px",
			fontFamily: "body",
			color: "fg.muted",
			flexShrink: 0,
		},
		suggestionKbd: {
			fontSize: "11px",
			fontFamily: "body",
			color: "fg.subtle",
			px: "6px",
			py: "2px",
			bg: "bg.secondary",
			borderRadius: "4px",
			marginLeft: "auto",
			flexShrink: 0,
		},
	},
	variants: {
		suggestionHighlighted: {
			true: {
				suggestionRow: {
					bg: "accent.subtle",
					_hover: {
						bg: "accent.subtle",
					},
				},
				suggestionText: {
					color: "fg.primary",
					fontWeight: "500",
				},
				suggestionIcon: {
					color: "fg.primary",
				},
			},
		},
	},
});
